### ISSUE TITLE
 Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead

### ISSUE THREAD

**Issue by CyberMixRo** [fabcd14/PadTool#1]
Hello,

I try to run on Ubuntu 18.04 and get this error:

`[Wdv ] Initializing WebDriver...
/home/dab/.local/lib/python3.6/site-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
[Wdv ] WebDriver initialization error : Message: Service phantomjs unexpectedly exited. Status code was: 1

Traceback (most recent call last):
  File "./padtool.py", line 132, in <module>
    main(sys.argv[1:])
  File "./padtool.py", line 115, in main
    templateLogo.generate(cfg, driver)
UnboundLocalError: local variable 'driver' referenced before assignment
`

**Comment by fabcd14** [comment]
Hello CyberMixRo,
It seems that PhantomJS has not been installed completely.
Have you installed PhantomJS with "sudo apt install phantomjs" and selenium with pip3 ?

I know that PhantomJS is deprecated, I'm actually looking for an alternative because Firefox and Chrome doesn't satisfy me at all at the moment. I have to do some deeper trials.
Please note that PadTool is not stable yet as it's a pre-release.

Thanks for your interest :)

**Comment by CyberMixRo** [comment]
Hello,

Thanks for answer I will try today as you suggest me. 

I have another question: How I can use this tool with ODR-PadEnc? Can you send me some example? I use ODR-PadEnc on supervisor.

PS. This tools is very interesting and I looking for this from few weeks. I really appreciate your effort and some beers come soon. :)

Thanks again

**Comment by CyberMixRo** [comment]
> sudo apt install phantomjs

Was already installed ... :( so is not that the problem

**Comment by CyberMixRo** [comment]
Ok, i come back with some news. I have make it to work with this mode for phantomjs: https://gist.github.com/julionc/7476620

Also i made to work with ODR-PadEnc, i got the idea of config but now i see as required some json files to get really what my station on test broadcast. Id not possible as future feature to use for cover itunes and for song title and artist or a txt file what have inside "artist - song title"?

**Comment by fabcd14** [comment]
Hello,
Sorry for my late reply.
Good to know for the PhantomJS installation link (i'll put that in the Install.md in the next commit).

For the moment, json format is privileged because it is a more structural way for data to be processed.
You can use the txt format with "$artist - $title" :

- In your config file, set [source]->format to txt
- To do the template, save a txt file with the following content : $artist - $title
- In your config file, set [source]->template to the path of your txt template file
- In your config file, set [source]->url to the path of your file where the artist and title is.

You don't need to have json files. :-)
In txt mode, only $artist and $title tags are supported.

For the moment, I don't know if there is such APIs relative to get the covers from iTunes. I'll looking for it, but as you might know it's not my priority at the moment. I would like to stabilize the process for json parsing, because some radios send different sized json files. :-)

Thanks for your support (and your beers btw) :-)

**Comment by CyberMixRo** [comment]
Hello,
Please if is possible, can you send me example of config and template files to extract from txt file artist - title?

About iTunes album cover image there is some python source on GitHub (I look faster for some example) here: https://github.com/matteing/coverpy

Thank you

Regards,
Florin ivan

**Comment by fabcd14** [comment]
Hello Florin,
Here is a configuration from a small french non-profit radio, which is using a txt file with artist and title. Before using it, rename the path of the template in your config file
[padtool-rbazar-conf.zip](https://github.com/fabcd14/PadTool/files/4113024/padtool-rbazar-conf.zip)

I'll have a deep look at this coverpy lib. 
Thanks for the tip :-)

**Comment by fabcd14** [comment]
Hello Florin,
The new pre-release v0.9.0 doesn't uses PhantomJS anymore.
Following your issue, I was looking for a way to use ChromeDriver instead of this to get rid of this warning, and I finally found it. It works with ChromeDriver (or ChromiumDriver).
Also, I added to the TODO list your question about covers.
Fabien.

**Comment by CyberMixRo** [comment]
Hello Fabien,

That's great, I will test today or tomorrow.

Thank you,

Regards
Florin Ivan

mar., 28 ian. 2020, 09:59 Fabien Cuny <notifications@github.com> a scris:

**Comment by CyberMixRo** [comment]
Hello,

I forgot to tell you as working now perfect with ChromeDriver.

Thanks

**Comment by fabcd14** [comment]
Hello,Glad to hear that :-)I hope to stabilize more the generation process in the future for long term running PadTool.Le 17 févr. 2020 14:36, CyberMixRo <notifications@github.com> a écrit :Hello,
I forgot to tell you as working now perfect with ChromeDriver.
Thanks
